---
- name: Git
  block:
    - name: Install git
      apt:
        name: git
        state: present
      when: ansible_os_family == 'Debian'

    - include_tasks: git_clone.yml
  when: gitops_clone | bool

- include_tasks: git_commit.yml
  when: gitops_commit | bool
